# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

movmean <- function(X, w) {
    .Call(`_PSNV_movmean`, X, w)
}

movmeanandstd <- function(X, w) {
    .Call(`_PSNV_movmeanandstd`, X, w)
}

movstd <- function(X, w) {
    .Call(`_PSNV_movstd`, X, w)
}

movsum <- function(X, w) {
    .Call(`_PSNV_movsum`, X, w)
}

pmsc_cpp <- function(Xr, w, rr) {
    .Call(`_PSNV_pmsc_cpp`, Xr, w, rr)
}

