# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

funcpp <- function(x) {
    .Call(`_PSNV_funcpp`, x)
}

movmean <- function(X, w) {
    .Call(`_PSNV_movmean`, X, w)
}

movmeanandstd <- function(X, w) {
    .Call(`_PSNV_movmeanandstd`, X, w)
}

