// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// movmean
NumericMatrix movmean(NumericMatrix X, int w);
RcppExport SEXP _PSNV_movmean(SEXP XSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(movmean(X, w));
    return rcpp_result_gen;
END_RCPP
}
// movmeanandstd
List movmeanandstd(Rcpp::NumericMatrix X, int w);
RcppExport SEXP _PSNV_movmeanandstd(SEXP XSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(movmeanandstd(X, w));
    return rcpp_result_gen;
END_RCPP
}
// movstd
NumericMatrix movstd(Rcpp::NumericMatrix X, int w);
RcppExport SEXP _PSNV_movstd(SEXP XSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(movstd(X, w));
    return rcpp_result_gen;
END_RCPP
}
// movsum
NumericMatrix movsum(NumericMatrix X, int w);
RcppExport SEXP _PSNV_movsum(SEXP XSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(movsum(X, w));
    return rcpp_result_gen;
END_RCPP
}
// pmsc_cpp
NumericMatrix pmsc_cpp(const NumericMatrix& Xr, int w, const NumericVector& rr);
RcppExport SEXP _PSNV_pmsc_cpp(SEXP XrSEXP, SEXP wSEXP, SEXP rrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Xr(XrSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type rr(rrSEXP);
    rcpp_result_gen = Rcpp::wrap(pmsc_cpp(Xr, w, rr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PSNV_movmean", (DL_FUNC) &_PSNV_movmean, 2},
    {"_PSNV_movmeanandstd", (DL_FUNC) &_PSNV_movmeanandstd, 2},
    {"_PSNV_movstd", (DL_FUNC) &_PSNV_movstd, 2},
    {"_PSNV_movsum", (DL_FUNC) &_PSNV_movsum, 2},
    {"_PSNV_pmsc_cpp", (DL_FUNC) &_PSNV_pmsc_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_PSNV(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
